### PR TITLE
Added reminder command

### LINKED ISSUE #29: Add: Create reminder command
Create a command `!remindme <time in seconds> <message>`. When the user runs this command, the bot should first acknowledge this command, and after given amount of time, sends a direct message to the user reminding them about their task or message.

### PR DESCRIPTION
**Pull request by ankan792**
Closes #29  
Added command `!remindme <time in seconds> <message>`

Screenshot 2022-10-10 164334

### CODE REVIEW

**Review by ankan792 — COMMENTED** [review]
deleted white space placed by accident

**Comment by z404** [comment]
Looks great @ankan792! Your fork seems to be behind by 2 commits, could you please update your fork so no code is lost? You'll be good to go after that!

**Comment by z404** [comment]
I'm sorry, I didn't specify properly in my message above, my mistake 😓 
You'll have to update the branch called [patch-2](https://github.com/ankan792/golly-bot/tree/patch-2) on your fork, since you have been developing there. Once you update, the "ping" command will show up in your code, then you know you've done it correctly.

**Comment by ankan792** [comment]
@z404 Sorry it's my bad. Looks like I didn't update properly last time. Hope it's good now haha.

**Review by z404 — APPROVED** [review]
LGTM! Good work :D

**Pull request merged**
