### PR TITLE
`add .env file` - using dotenv file to store/load secrets

### LINKED ISSUE #7: Add: env file
Add a `.env` file to the repository, with settings like the bot's token, the bot's prefix, and any other settings you see fit. Make sure that the `.env` file is present in the `.gitignore` file so it doesn't accidentally get committed. Add a sample `.env.sample` file with the same fields as the `.env` but without the values so other users know the structure of the file. 

Read the file (along with error handling) in the `init` function of `main.go`

### PR DESCRIPTION
**Pull request by nkilm**
## Fixes #7
Use .env file to load/store environment variables into the program, `.env.sample` file describes how the .env file should be on the local system. Exact variable names should be used as described in .env.sample.

### CODE REVIEW

**Comment by z404** [comment]
Hi @nkilm, this looks great! Could you also put the bot prefix in the `.env` file? It provides easy customization for anyone who wants to change the bot prefix

**Comment by nkilm** [comment]
@z404 Okay!

**Comment by nkilm** [comment]
#### Amended last commit to keep commit history clean and force pushed.

**Comment by z404** [comment]
This is perfect. Your branch seems to be behind this repository by 2 commits, bring it up to date and you're good to go!

**Comment by nkilm** [comment]
@z404 Done!

**Review by z404 — APPROVED** [review]
Looks great, good work!

**Comment by ankan792** [comment]
@nkilm have you run the code and see if it is working?

**Comment by nkilm** [comment]
@ankan792 I seldom use discord, but you can test it in your system.

**Comment by ankan792** [comment]
@nkilm It's always a good practice to run and review the code before commiting changes.

**Pull request merged**
